# THIS IS ONLY A TEMPLATE FILE - Below are the all enviroment variable (with possible default values) that need to work this program smoothly.
# CREATE NEW FILE CALLED "backend-secrets.yml" with necessary values to these variables.

# Make sure this "secret object config" (With necessry values filled) is executed before backend.yml is deployed.
# kubectl apply -f backend-secrets.yml

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  # These secrets are later used by "backend.yml" and in there inject them into container as env. varaibles.
  # Note that this secrets are available to any deployment file to refer(if necessary), not just backend.yml
  NODE_ENV: "production"
  PORT: "80"
  CORS_WHITE_LIST: "http://hb-frontend-service/"

  DBNAME: "hackerbay"
  DBUSERNAME: "devadmin"
  DBPASSWORD: "devadmin"
  DBHOST: "postgresdb-service"

  JWTSECRET: "mySuperSecretsP4$$w0rD"
  JWTEXPIRES: "3600s"

  TWILIO_SID: ""
  TWILIO_TOKEN: ""
  TWILIO_NUMBER: ""